Add bookings
MaxGoodfella/java-shareit pull request #2
Opened 2024-05-13 21:31 UTC by MaxGoodfella

2024-05-15 03:54 UTC, sergeymamonov requested changes
Лучше давать осмысленные названия коммитам, так легче ориентироваться в истории.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        for (Booking booking : bookings) {
Сложный код в этом цикле. Код сложно читаемый. Лучше упростить. Вынести часть кода в подметоды.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    if (!(state.equalsIgnoreCase("WAITING")
Я бы раньше провалидировал state и в этот метод передавал уже перечисление.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    if (booking.getStatus() != null) {
Разве это не то же самое, что и state строчкой выше? Если да, то нужно упростить.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exceptions/BadRequestException.java
> +        super("Entity '" + entityClass.getSimpleName() + "' cannot be requested. " + message);
Я бы не через канкатенацию делал, а через String.format(). На мой взгляд, поаккуратнее бы выглядело. Плюс при откладке будет полезна не информация о классе. А id или другая информация, которая идентифицирует запрос, сущность к которой сделан запрос и так далее.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        ItemDtoOut itemDtoOut = ItemMapper.toItemDtoOut(itemGet.get());
Строкой выше создан item.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<CommentDtoOut> getAllItemComments(Integer itemId) {
Можно сделать private.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            if (userRepository.findByEmail(updatedUser.getEmail()) != null) {
Обращайте внимание на подсказки среды разработки. В данном случае можно объединить два if в один с помощью &&.

2024-05-15 03:54 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    name VARCHAR NOT NULL,
Размер varchar лучше ограничивать.

2024-05-15 14:10 UTC, MaxGoodfella commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    if (booking.getStatus() != null) {
Нет, это не то же самое, так как у меня два enum-класса с перечислением и это разные поля) Одно используется только внутри программы (пользователь его не видит), а другое со статусами WAITING, APPROVED, REJECTED, CANCELED он видит. Поэтому сначала надо до default дойти, а в нём уже проверить.

2024-05-15 17:47 UTC, sergeymamonov approved these changes

2024-05-15 17:47 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                case "CURRENT":
Что точно можно сделать лучше. Выше есть статусы "CURRENT", "PAST" и др. и это строки. Я бы сделал перечисление.

2024-05-15 17:47 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                                if (booking.getStatus().name().equalsIgnoreCase(state)) {
А такое может быть? Не вижу пересечений этих перечислений.

2024-05-15 17:47 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exceptions/AccessDeniedException.java
> +        super(String.format("No access allowed to entity '%s' for user with ID '%s'. %s",
Да, теперь искать причину будет легче.

2024-05-16 12:17 UTC, MaxGoodfella commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                                if (booking.getStatus().name().equalsIgnoreCase(state)) {
А тут и нет пересечений этих пересечений, тут как раз идёт по статусу просто, так как полей статусов у меня 2.

2024-05-16 12:18 UTC, MaxGoodfella commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                case "CURRENT":
Прошу прощения, а выше это где?)

2024-05-16 12:19 UTC, merged