Microservices & docker
MaxGoodfella/java-shareit pull request #4
Opened 2024-06-09 19:26 UTC by MaxGoodfella

2024-06-13 04:11 UTC, sergeymamonov requested changes
Указывать зависимости в родительском помнике не очень хорошая практика. Лучше указывать все зависимости в дочерних помниках. Пример, нужна зависимость для каждого из подмодулей, но в одном нужна версия 1, а во втором версия 2. Если указывать зависимость в дочерних помниках, то легко указать в одном одну версию, а во втором другую версию.

2024-06-13 04:11 UTC, sergeymamonov commented on README.md
> +разобраться вместе с наставником, он попытался помочь, высказав предположение, но не сработало.
Тут сходу не подскажу, не встречал, чтобы для одного модуля настраивали джакоко.

2024-06-13 04:11 UTC, sergeymamonov commented on shareIt-gateway/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                                  defaultValue = "0") Long from,
Цель сервиса gateway валидировать входящие данные. Здесь же можно передать отрицательное число и оно уйдет в основной сервис.

2024-06-13 04:11 UTC, sergeymamonov commented on shareIt-gateway/src/main/java/ru/practicum/shareit/request/dto/RequestDto.java
> +@Setter
Тут не может быть сеттера.

2024-06-13 04:11 UTC, sergeymamonov commented on shareIt-gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Setter
Тут не может быть сеттера.

2024-06-13 04:11 UTC, sergeymamonov commented on shareIt-gateway/src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +@Setter
Тут не может быть сеттера.

2024-06-13 04:11 UTC, sergeymamonov commented on shareIt-gateway/src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Setter
Тут не может быть сеттера.

2024-06-13 04:11 UTC, sergeymamonov commented on pom.xml
> +<!--				<plugin>-->
Не оставляйте закомментированного кода.

2024-06-13 04:25 UTC, sergeymamonov requested changes
У всех dto не должно быть сеттеров.

PaginationValidator - не должно быть в основном сервисе.

2024-06-13 04:25 UTC, sergeymamonov commented on README.md
> +Также извиняюсь за грязь в коммит-истории (очень много подводных камней оказалось, даже просил друга с
Можно склеивать коммиты, ammend и так далее, вариантов много, как сделать красивую историю в гите. Погуглите возможности гита.

2024-06-13 04:25 UTC, sergeymamonov commented on shareIt-server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    void validateState(String state) {
Не очень хороший способ валидации. Если добавится новое значение в перечисление, а здесь это значение забудут добавить, то будет ошибка. Хотя ее быть не должно. Поэтому я бы переделал валидацию.

2024-06-13 04:25 UTC, sergeymamonov commented on shareIt-server/src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    public int getStatusValue() {
Зачем писать геттер, если есть аннотация?

2024-06-13 04:25 UTC, sergeymamonov commented on shareIt-server/src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    public ErrorResponse(String error, HttpStatus status) {
Лучше воспользоваться аннотацией Ломбок, чем писать руками конструктор.

2024-06-13 17:00 UTC, MaxGoodfella commented on README.md
> +разобраться вместе с наставником, он попытался помочь, высказав предположение, но не сработало.
Я просто к тому, что на данный момент покрытие заходит в gateway, а из-за этого снижается процент покрытия)

2024-06-16 04:06 UTC, sergeymamonov commented on README.md
> +разобраться вместе с наставником, он попытался помочь, высказав предположение, но не сработало.
По-хорошему, сервис gateway также должен быть покрыт тестами)

2024-06-16 04:18 UTC, sergeymamonov approved these changes
Замечание про сеттеры не устранено.

2024-06-16 04:18 UTC, sergeymamonov commented on pom.xml
>  	</dependencies>
В родительском помнике не должно быть зависимостей.

2024-06-16 04:18 UTC, sergeymamonov commented on shareIt-server/src/test/java/ru/practicum/shareit/paginationvalidation/PaginationValidatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Лучше отказаться от такого типа импорта даже в тестах.

2024-06-16 08:33 UTC, merged